# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43c47f6eb099ab25875b91ed48baad7161d42cd900cbc61db478401e816a9ec63785b85757bd7271a21db1f00af2773655da673119a4c2a03804744beef4b77

test:
  secret_key_base: 641bee9ae0760bd64f8de1109d9c522995ed635291aca6c443aeee6ae95c41f68e1d65bed50c54275aa9a5e830764cbd3b095cd5f8e8c7e95ecc0b9504f47c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
